tables:
#CREATE TABLE `account` (
#  `id` varchar(50) NOT NULL default '',
#  `email` varchar(255) default NULL,
#  `password` varchar(255) default NULL,
#  `activated` int(11) default NULL,
#  `activate_key` varchar(50) default NULL,
#  `activate_password` varchar(255) default NULL,
#  `activate_date` datetime default NULL,
#  `change_email_email` varchar(255) default NULL,
#  `change_email_key` varchar(50) default NULL,
#  `change_email_date` datetime default NULL,
#  PRIMARY KEY  (`id`)
#) ENGINE=InnoDB DEFAULT CHARSET=latin1;        
  account:
    _description: Account.
    field:
      id:
        type: varchar(50)
        not_null: true
        primary_key: true
      email: 
        type: varchar(255)
        default: 'null'
      password: 
        type: varchar(255)
        default: 'null'
      activated: 
        type: int(11)
        default: 'null'
      activate_key: 
        type: varchar(50)
        default: 'null'
      activate_password: 
        type: varchar(255)
        default: 'null'
      activate_date: 
        type: datetime
        default: 'null'
      change_email_email: 
        type: varchar(255)
        default: 'null'
      change_email_key: 
        type: varchar(50)
        default: 'null'
      change_email_date: 
        type: datetime
        default: 'null'
#CREATE TABLE `account_log` (
#  `id` int(16) NOT NULL auto_increment,
#  `account_id` varchar(50) default NULL,
#  `type` varchar(50) default NULL,
#  `date` datetime default NULL,
#  PRIMARY KEY  (`id`),
#  KEY `account_id` (`account_id`),
#  CONSTRAINT `account_log_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
#) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=latin1;        
  account_log:
    _description: Account log.
    field:
      id:
        type: int(16)
        not_null: true
        auto_increment: true
        primary_key: true        
      account_id: 
        type: varchar(50)
        default: 'null'
        foreing_key:
          reference_table: account
          reference_field: id
          on_delete: CASCADE
          on_update: CASCADE        
      type: 
        type: varchar(50)
        default: 'null'
      date:
        type: datetime
        default: 'null'

#CREATE TABLE `account_role` (
#  `id` int(16) NOT NULL auto_increment,
#  `account_id` varchar(50) default NULL,
#  `role` varchar(50) default NULL,
#  PRIMARY KEY  (`id`),
#  KEY `account_id` (`account_id`),
#  CONSTRAINT `account_role_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
#) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=latin1;
  account_role:
    _description: Account roles.
    field:
      id:
        type: int(16)
        not_null: true
        auto_increment: true
        primary_key: true        
      account_id: 
        type: varchar(50)
        default: 'null'
        foreing_key:
          reference_table: account
          reference_field: id
          on_delete: CASCADE
          on_update: CASCADE
      role:
        type: varchar(50)
        default: 'null'
      
        
        
        
        