tables:
  account:
    _description: Account.
    field:
      id:
        type: varchar(50)
        not_null: true
        primary_key: true
      email: 
        type: varchar(255)
        default: 'null'
      password: 
        type: varchar(255)
        default: 'null'
      activated: 
        type: int(11)
        default: 'null'
      activate_key: 
        type: varchar(50)
        default: 'null'
      activate_password: 
        type: varchar(255)
        default: 'null'
      activate_date: 
        type: datetime
        default: 'null'
      change_email_email: 
        type: varchar(255)
        default: 'null'
      change_email_key: 
        type: varchar(50)
        default: 'null'
      change_email_date: 
        type: datetime
        default: 'null'
      phone:
        type: varchar(255)
        default: 'null'
      two_factor_authentication_key: 
        type: varchar(50)
        default: 'null'
      two_factor_authentication_date: 
        type: datetime
        default: 'null'
      cert_id:
        type: varchar(255)
        default: 'null'
  account_log:
    _description: Account log.
    field:
      id:
        type: int(16)
        not_null: true
        auto_increment: true
        primary_key: true        
      account_id: 
        type: varchar(50)
        default: 'null'
        foreing_key:
          reference_table: account
          reference_field: id
          on_delete: CASCADE
          on_update: CASCADE        
      type: 
        type: varchar(50)
        default: 'null'
      date:
        type: datetime
        default: 'null'
  account_role:
    _description: Account roles.
    field:
      id:
        type: int(16)
        not_null: true
        auto_increment: true
        primary_key: true        
      account_id: 
        type: varchar(50)
        default: 'null'
        foreing_key:
          reference_table: account
          reference_field: id
          on_delete: CASCADE
          on_update: CASCADE
      role:
        type: varchar(50)
        default: 'null'
extra:
  _description: Extra field to add to each table if not exist in schema.
  field:
    created_at:
      type: timestamp
      default: CURRENT_TIMESTAMP
    updated_at:
      type: timestamp
      default: 'null'
    created_by:
      type: varchar(50)
    updated_by:
      type: varchar(50)
      
        
        
        
        